language: node_js
node_js:
- '4'
- '5'
sudo: false
env:
  global:
    - secure: bxOpzUNUvrisqHWKESwTB4AOG6vm2+flQw/fSFn59HIDx70E76SrIKE6J9ledA7DSMN/l23/bOMkS72sf+AFaYr4jXel74LOm++x2G3qpsTTx+zw5B00/l09pWaE6W8/Ljk2RXL3bagmOyfHum+Xjp/ABeTXdLQkRT8XlENlvW2h5yG1w7f02acNY8l/DDYXYh+rtLMplJV8+633ZzRyHrSDzQJ7dm0AK6r+Dm+ITWBW7Hs59K40pO6EpXyMngLajZafcEtrVvSwScl7FVH4xIGJTDfeThR7atwc0weHNMqU74uerxu0uj6zyo7l4ARJPeGWoq7httuqfaF5RsEvGhS0DW2BdmDUJqzVCvo5u5sZay18Ay8tbndbXJkY5rK1FnOxePubr72qOj2LkZrosFBiwsjydaGGe3wHUTg3d/4cPcVQOE+x4Fr1v2NixsHED0x6OdVKQ7sQkLKXoAF7zOrSWW/CfnC0fN1ejML0i3BTeTny8Th5HnPa7TYRFJJXFTQc5jxUettv1/VH2IFtH5seJqltB6HkCqyQOyxW3aUgZw5Lq1NVGOoKSw4YZYAatIpSIfALjwGqAHQIjMZaF2gbtRCCLecRDngxn+b4PoBA1qQsEPDgROZxumWEPXEvh+zzKdtFko65t82qRAu1VB5IAENCWdKGSE9IGqk4e50=
after_success:
- cat coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
