language: node_js
node_js:
- '4'
- '5'
sudo: false
env:
  global:
  - secure: qDb9Tx5RQ53fGB375GUV19C/poc9Q14xbdNWYIrNdnMzJgkNGsnS28pWgsjVIuT+FBXmm2xFtPyZB14ifYyYI8T3SMv/+ifOrI0Pl6zDTV5f8/OI7COta8+mVcfEZDYSPM/9WX59xZFlrbhxGMZrDdgVDxkV+sxZ6uzzZZpC25IBClrM3kcy7+WezTDXpWnRtFv1GW6f5sqRMIsmSvK6FDWqsw2LWwCXF7a6mapVLPlj9Xv2nOlCXL2zAfgYb1eXY+GYu4tZAbqMepH0GjSJT9UMw55buKbcEmJvajm7CYbQ2z5PGbFHLBj3vJDIvVJrCuJypDlJeq7tzjnil6byIWHIOntVi8svc7Kk6A/h/Pe/D/VJYt1Y0f+ISia8koD0ZXBouIWmu60SCKzqtq7AlFE82BdXAuBBb4gem6N3AwvLp2hYPMrgZwl5H8t57rdLR0zhQ6YqhlO5gheRnAtocJX86iTq+SGQcCuufiLyYpDl85LM2z21Ta4JBCEmpy00qc4reoITtbRkXXDaIxuhKBjfysJtyP/5qjHhoGXbZ7OGbxVwG/TNK4FpnUVtO0+pyrZaIvUuyNGtDtliwjHijz7ucZ12Emd9BUkNVwAlKRVHDxhOwncBsGO0TtYCRMex59WIWqXiR4A6A3R5cWq4fclNvQIuqqdhNvUoqbs5haE=
after_success:
- cat coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
